.TH LIBOYSTR 7 liboystr
.SH NAME
liboystr - Mollusc flavored string library
.SH Description
.B liboystr
is a C library for dynamic string handling. The goals of this library are to be 
small, and fast.
.P
.B liboystr
approaches C string handling in a rather traditional way, using a C structure to
contain both a NULL-terminated string buffer, and integer fields keeping track
of it's size and length.

.SS oystr format
The oystr string struct is a simple one, and all of it's fields are open to
direct modification as long as the oystr remains valid after doing so.
.PP
.in +4n
.nf
oystr {
	size_t len;  // Length of used bytes in \fIbuf\fP.
	size_t size; // Size of the \fIbuf\fP field.
	char *buf;   // Character buffer.
};
.fi
.in
.PP
A valid oystr is defined as one where
.I buf
!= NULL,
.I len
<
.IR size ,and
.I size
!= 0.
An example of an inconsistent modification that will break many oystr
functions is something like changing the \fIsize\fP field without changing 
the actually allocated length of \fIbuf\fP.
.SH RATIONALE
Many string library unnecessarily force the user to allocate memory twice, for
one string (GLib GString), don't properly check for unsigned integer overflows
(bstrlib), or repeatedly validate function input over and over (bstrlib).
.PP
.B liboystr
functions do no input validation, but there is a provided validation function
provided. This allows the caller to validate an oystr when it is most 
appropriate, rather than penalize the caller by unnecessarily checking in every 
single call into the library.
.SH AUTHOR
Written by Todd O. Gaunt.
.SH SEE ALSO
.BR oystr_append (3),
.BR oystr_assign (3),
.BR oystr_avail (3),
.BR oystr_deinit (3),
.BR oystr_ensure_size (3),
.BR oystr_eq (3),
.BR oystr_find (3),
.BR oystr_init (3),
.BR oystr_insert (3),
.BR oystr_set_len (3),
.BR oystr_slice (3),
.BR oystr_strip (3),
.BR oystr_swap (3),
.BR oystr_trunc (3),
.BR oystr_utf8_from_utf32 (3),
.BR oystr_valid (3),
.BR oystr_write (3),
