.TH istrlib 3 istrlib\-VERSION
.SH NAME
istrlib \- Improved String Library
.SH SYNOPSIS
.B #include <istrlib.h>
.PP
.B typedef struct 
.I istring istring;
.SH DESCRIPTION
The istring library (hereafter referred to as istrlib) is an efficient and 
simple dynamic string library for C. It provides the istring structure and 
functions that operate on them. istrings are fully compatible with the 
standard ANSI C <string.h> functions with access to their character buffers.
however, an istring is not required to contain a terminating null-byte and
none of the library functions require a terminating null-byte unless 
specifically required (For interoperability with existing C strings).
As a bonus because of this, istrings can be used to hold arbitrary data
inside of them with no worries of the library modifying the data in unexpected
ways (istrlib will NEVER automatically insert a null-byte for you).
.PP
istrlib includes utf8 helper functions that let unicode characters be
manipulated by the number of unicode characters rather than the size in bytes.
.PP
Memory allocation for istrings is also efficient, as the scheme for increasing
an istring's size is to keep it as a power of two e.g. 32, 64, 512.
.PP
.SH FUNCTIONS
.I For more detailed documentation please look at istrlib.h
.TP
.B istr_new
Copy or initialize a new istring.
.TP
.B istr_new_bytes
Initialize a new istring with arbitrary bytes.
.TP
.B istr_new_cstr
Initialize a new istring with a string with terminating null-byte.
.TP
.B istr_free
Free all memory allocated to an istring structure.
.TP
.B istr_str
Get a pointer to the char buffer in the given istring.
.TP
.B istr_len
Get the amount of bytes contained by the given istring.
.TP
.B istr_size
Get the size allocated to the given istring's character buffer.
.TP
.B istr_assign_bytes
Reassign an istring's contents to arbitrary bytes, rewriting any old contents.
.TP
.B istr_assign_cstr
Reassign an istring's contents to a string with a terminating null-byte.
.TP
.B istr_eq
Check if two istings contain the same contents.
.TP
.B istr_truncate_bytes
Shorten's the istring to a specified length.
.TP
.B istr_pop_byte
Removes the last byte in an istring and returns it.
.TP
.B istr_write
Overwrites an istring at an index with another istring.
.TP
.B istr_write_bytes
Overwrites an istring at an index with arbitrary bytes.
.TP
.B istr_prepend
Prepends a copy of an istring to another istring.
.TP
.B istr_prepend_bytes
Prepends arbitrary bytes onto an istring.
.TP
.B istr_append
Appends a copy of an istring to another istring.
.TP
.B istr_append_bytes
Appends arbitrary bytes onto an istring.
.TP
.B istr_insert
Inserts an istring into an istring at an index without overwriting.
.TP
.B istr_insert_bytes
Inserts arbitrary bytes into an istring at an index without overwriting.
.SH CONFORMING TO
The
.I istrlib
library is guaranteed to conform with C99 or later
.SH AUTHOR
Written by Todd O. Gaunt
