.TH STXALLOC 3 libstx
.SH NAME
 stxalloc - Allocate memory in a stx for a number of bytes.
.SH SYNOPSIS
.B #include <libstx.h>

.B int stxalloc(stx *\fIsp\fP, size_t \fIsize\fP);
.SH DESCRIPTION
.B stxalloc()
allocates memory for
.I sp->mem
then sets
.I sp->len
to 0, and
.I sp->size
to
.IR size .
.SH RETURN VALUE
.B stxalloc()
returns s0 upon a successful allocation. Returns -1 if the allocation fails.
.SH SEE ALSO
.BR libstx (7),
.BR stxensure_size (3),
.BR stxgrow (3)
