.TH STXAPP 3 libstx
.SH NAME
stxapp_mem, stxapp_str, stxapp_uni, stxapp_spx - append byts to a stx.
.SH SYNOPSIS
.B #include <libstx.h>

.B stx *stxapp_mem(stx *\fIsp\fP, const char *\fIsrc\fP, size_t \fIn\fP);

.B stx *stxapp_str(stx *\fIsp\fP, const char *\fIsrc\fP);

.B stx *stxapp_utf8f32(stx *\fIsp\fP, uint32_t \fIwc\fP);

.B stx *stxapp_spx(stx *\fIsp\fP, const spx \fIsrc\fP);
.SH DESCRIPTION
.BR stxapp_mem ()
appends
.I n
bytes from
.I src
to
.IR sp->mem .
.P
.BR stxapp_str ()
appends
.I src
to
.IR sp->mem .
until a null byte is reached.
.P
.BR stxapp_uni ()
converts
.I wc
from a utf32 unicode code point character to it's corresponding utf8 byte
sequence, then appends that utf8 byte sequence to the end of
.IR sp->mem .
.P
.BR stxapp_spx ()
appends
.I src.mem 
to
.IR sp->mem .
.P
If
.I src
is NULL or
.I n
is 0, then
.IR sp
is zero initialized. This is considered a successful appendation.
.SH RETURN VALUE
.BR stxapp_mem (),
.BR stxapp_str (),
.BR stxapp_utf8f32 (),
and
.BR stxapp_spx ()
always return a pointer to
.I sp
to allow for function composition.
.SH SEE ALSO
.BR libstx (7)
.BR stxutf (3)
