.TH STXENSURE_SIZE 3 libstx
.SH NAME
stxensure_size - Ensure a that a stx can contain at least a minimum amount of
bytes.
.SH SYNOPSIS
#include <libstx.h>

int stxensure_size(stx *sp, size_t size);

#include <libstx.hpp>

int libstx::ensure_size(stx *sp, size_t size);
.SH DESCRIPTION
.B stxensure_size()
and
.B libstx::ensure_size()
check if the memory buffer of
.I sp
can contain at least
.I size
bytes. If the memory buffer cannot contain the requested amount of bytes, it
will be resized to hold at exactly that many bytes. Otherwise, no action will
be performed.
.SH RETURN VALUE
.B stxensure_size()
and 
.B libstx::ensure_size()
return 0 if the memory reallocation was successful, or -1 if the
reallocation failed (The memory buffer is untouched in this case).
.SH SEE ALSO
.BR liboystr (7)
