.TH STXGROW 3 libstx
.SH NAME
stxgrow - Grow the amount of bytes a stx can contain exactly by a given number.
.SH SYNOPSIS
#include <libstx.h>

int stxgrow(stx *sp, size_t n);
.SH DESCRIPTION
.B stxgrow()
reallocates
.I sp->mem
by
.I n
bytes. If the size of the the buffer would overflow SIZE_MAX, an attempt is made
to reallocate the memory buffer to SIZE_MAX instead, and set the size accordingly.
.SH RETURN VALUE
.B stxgrow()
returns 0 if the memory reallocation was successful. Returns -1 if the
reallocation fails (
.I sp
was unmodified in this case).
.SH SEE ALSO
.BR liboystr (7)
