.TH STXGROW 3 libstx
.SH NAME
stxgrow - Grow the amount of bytes a stx can contain exactly by a given number.
.SH SYNOPSIS
.B #include <libstx.h>

.B int stxgrow(stx *sp, size_t n);
.SH DESCRIPTION
.BR stxgrow ()
grows
.I sp->mem
by
.I n
bytes. If the size of the the buffer would overflow SIZE_MAX, an attempt is made
to reallocate the memory buffer to SIZE_MAX instead, and set the size accordingly.
.P
If
.I n
is 0, no modification is done to
.IR sp .
.SH RETURN VALUE
.BR stxgrow ()
returns 0 if the memory reallocation was successful. Returns -1 if the
reallocation fails
.RI ( sp
was unmodified in this case).
.SH SEE ALSO
.BR libstx (7)
